= Policy Bundles

:numbered:

The policies and the data used by the policies are available as OCI artifacts
compatible with the `conftest pull` command.

== Location

The latest versions of the bundles can be found in the following repos:

https://quay.io/repository/enterprise-contract/ec-release-policy?tab=tags[`quay.io/enterprise-contract/ec-release-policy`]::

Used for validating attestations created by Tekton Chains. Contains the
contents of https://github.com/enterprise-contract/ec-policies/tree/main/policy/release[`policy/release`]
and https://github.com/enterprise-contract/ec-policies/tree/main/policy/lib[`policy/lib`]
in this repo.

https://quay.io/repository/enterprise-contract/ec-pipeline-policy?tab=tags[`quay.io/enterprise-contract/ec-pipeline-policy`]::

Used for validating Tekton Pipeline definitions. Contains the contents of
https://github.com/enterprise-contract/ec-policies/tree/main/policy/pipeline[`policy/pipeline`]
and https://github.com/enterprise-contract/ec-policies/tree/main/policy/lib[`policy/lib`].

== Artifact Hub entries

The bundles mentioned above are also listed in https://artifacthub.io/packages/search?org=enterprise-contract[Artifact Hub].

== Example usage

The bundles are designed to be used with the xref:_@ec-cli::index.adoc[ec-cli], but you
can also use them with conftest directly. The input should include a top level key called `attestations` which contains a list of
attestations for the image being validated. For example:

```
cosign download attestation quay.io/konflux-ci/ec-golden-image:latest | jq --slurp '{"attestations":[.[].payload|@base64d|fromjson]}' > input.json
conftest pull -p . quay.io/enterprise-contract/ec-release-policy quay.io/enterprise-contract/ec-policy-data
conftest test input.json -d data -p policy --all-namespaces -o json | yq -P
```
