= Task Policy

:numbered:

These rules are applied to Tekton task definitions.

== Available policy packages

[cols="2,6"]
|===
|*Package Name*
|*Description*

| xref:packages/step_images_package.adoc[step_images]
a| This package ensures that a Task definition contains valid values for the image references used by the Task's steps.

| xref:packages/step_image_registries_package.adoc[step_image_registries]
a| This package ensures that a Task definition contains expected values for the image references used by the Task's steps.

| xref:packages/annotations_package.adoc[annotations]
a| Policies to verify that a Tekton Task definition uses well formed expected annotations .

| xref:packages/results_package.adoc[results]
a| Verify Tekton Task definitions provide expected results.

| xref:packages/kind_task_package.adoc[kind]
a| Policies to verify that a Tekton task definition has the expected value for kind.

| xref:packages/trusted_artifacts_package.adoc[trusted_artifacts]
a| Policies to verify that a Tekton task definition conforms to the expected conventions required for using Trusted Artifacts.

|===
