= Task Policy

:numbered:

These rules are applied to Tekton task definitions.

== Available Packages

[cols="2,6"]
|===
|*Package Name*
|*Description*

| xref:packages/task_step_images.adoc[step_images]
a| This package ensures that a Task definition contains valid values for the image references used by the Task's steps.

| xref:packages/task_step_image_registries.adoc[step_image_registries]
a| This package ensures that a Task definition contains expected values for the image references used by the Task's steps.

| xref:packages/task_annotations.adoc[annotations]
a| Policies to verify that a Tekton Task definition uses well formed expected annotations .

| xref:packages/task_results.adoc[results]
a| Verify Tekton Task definitions provide expected results.

| xref:packages/task_kind.adoc[kind]
a| Policies to verify that a Tekton task definition has the expected value for kind.

| xref:packages/task_trusted_artifacts.adoc[trusted_artifacts]
a| Policies to verify that a Tekton task definition conforms to the expected conventions required for using Trusted Artifacts.

|===
