= Trusting Bundles

:acceptable-bundles: acceptable_bundles.adoc
:attestation-task-bundle: release_policy#attestation_task_bundle_package
:build-definitions: https://github.com/redhat-appstudio/build-definitions
:ec-policies: https://github.com/enterprise-contract/ec-policies
:ec-track-bundle: https://enterprisecontract.dev/docs/ec-cli/main/ec_track_bundle.html
:tekton-bundles: https://tekton.dev/docs/pipelines/pipelines/#tekton-bundles

This document details the process of trusting a link:{tekton-bundles}[Tekton Bundle]. The term
xref:{acceptable-bundles}[acceptable bundle] refers to a trusted Tekton Bundle.

When evaluating a certain input, certain policy rules enforce that only acceptable bundles were
used. The xref:{attestation-task-bundle}[Attestation Task Bundle] package, for example, performs
this check on SLSA Provenance attestations.

To reduce errors, use the link:{ec-track-bundle}[ec track bundle] command to manage entries in the
list of acceptable bundles. The command adds a list of Tekton Bundles to an existing list of
acceptable bundles. It can also generate a new list of acceptable bundles.

For example, consider the two hypothetical Tekton Bundle, `example.com/org/bacon:v1.0` and
`example.com/org/spam:v2.0`. These Tekton Bundles each include one or more Tekton Tasks. The snippet
below illustrates how to generate a new list of acceptable bundles containing the example Tekton
Bundles.

[,bash]
----
$ date
Thu Apr 13 02:21:56 PM EDT 2023

$ ec track bundle \
    --bundle example.com/org/bacon:v1.0 \
    --bundle example.com/org/spam:v2.0 \
    --output acceptable-bundles.yaml

$ cat acceptable-bundles.yaml
---
task-bundles:
  example.com/org/bacon:
    - digest: sha256:311fe3feed16b9cd8df0f8b1517be5cb86048707df4889ba8dc37d4d68866d02
      effective_on: "2023-05-14T00:00:00Z"
      tag: "v1.0"
  example.com/org/spam:
    - digest: sha256:5a2928bc8e2936d8885460d7b7f22e9d407bca1ed847d709b7fd4115a7679e3b
      effective_on: "2023-05-14T00:00:00Z"
      tag: "v2.0"
----

NOTE: The `ec track bundle` command marks new entries as required in 30 days. This gives users a
reasonable time-window to update.

Now, imagine a new Tekton Bundle is available at `example.com/org/bacon:v1.1`. Add this new Tekton
Bundle to the existing list of acceptable bundles like this:

[,bash]
----
$ ec track bundle \
    --bundle example.com/org/bacon:v1.1 \
    --input acceptable-bundles.yaml \
    --replace

$ cat acceptable-bundles.yaml
---
task-bundles:
  example.com/org/bacon:
    - digest: sha256:9cca0703342e24806a9f64e08c053dca7f2cd90f10529af8ea872afb0a0c77d4
      effective_on: "2023-05-14T00:00:00Z"
      tag: "v1.1"
    - digest: sha256:311fe3feed16b9cd8df0f8b1517be5cb86048707df4889ba8dc37d4d68866d02
      effective_on: "2023-05-14T00:00:00Z"
      tag: "v1.0"
  example.com/org/spam:
    - digest: sha256:5a2928bc8e2936d8885460d7b7f22e9d407bca1ed847d709b7fd4115a7679e3b
      effective_on: "2023-05-14T00:00:00Z"
      tag: "v2.0"
----

Be sure to include the `acceptable-bundles.yaml` file in a data source in your policy configuration.

== An Example

Automation using the process described above manages the acceptable bundles used in Konflux. This section describes how.

The repository link:{build-definitions}[redhat-appstudio/build-definitions] contains all the Tekton
definitions used by Konflux. The CI/CD process on that repository performs the following actions:

1. Determine which Tekton definitions have modifications.
2. Build a new Tekton Bundle for each modified Tekton definition.
3. Use the `ec track bundle` command to create a new list of acceptable bundles.
4. Submit a new pull request to the link:{ec-policies}[ec-policies] repository. The pull request
   includes the new list of acceptable bundles.

The new Tekton Bundles become acceptable bundles as soon as the pull request merges.

== Adding a new acceptable bundle to Konflux

The process to add a new task defintion to the existing Red Hat acceptable task list is relatively uncomplicated and is detailed below.

Before adding a new task, however, there are a few things to consider:

* The added task should have a wide audience for usage. Tasks added to the build definitions repository should not be specific to a single product or team.
* Submitting a task to the build-definitions repository has the practical effect of marking a task as "trusted" by Red Hat.
* To discuss your idea for a new task, visit the #forum-konflux-build channel on the Red Hat Developer Slack.

In order to add a new task to the existing set of Red Hat acceptable tasks, the process is as follows:

* https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo[Fork] the https://github.com/redhat-appstudio/build-definitions[build defintions] repository.
* Create and submit a https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request[pull request] with your new task.
* Once the pull request is submitted and approvevd, the CI process will automatically build the new task and add it to the list of acceptable tasks.
** You may view the acceptable bundles xref:{acceptable-bundles}[here].
** Additionally, you can view the task bundle in the https://quay.io/redhat-appstudio-tekton-catalog[Red Hat AppStudio Tekton Catalog]

== Adding a custom task to the trusted task list

Some users may want to add a custom build task to the default acceptable bundles list without pushing that task to the upstream acceptable task list. Below is a possible approach to make that happen.

EC requires a customized policy in order to accept a custom task. Such a policy must include an additional data source with task bundle refs and digests relevant to the new custom task.

For example, starting with https://github.com/enterprise-contract/config/blob/main/redhat-no-hermetic/policy.yaml[Red Hat's non-hermetic build policy], a new data source can be added under the `sources.data` key. See https://github.com/simonbaird/securesign-ec-config/blob/main/policy.yaml#L24[this policy] for a complete example.

[,bash]
---
name: Secure Sign Custom Enterprise Contract Policy

description: >-
  Based on the standard Red Hat (non hermetic) policy
  (see https://github.com/enterprise-contract/config/blob/main/redhat-no-hermetic/policy.yaml)
  but with one additional data source.

publicKey: "k8s://openshift-pipelines/public-key"

sources:
  - name: Default with extra source
    policy:
      - github.com/enterprise-contract/ec-policies//policy/lib
      - github.com/enterprise-contract/ec-policies//policy/release

    data:
      - oci::quay.io/redhat-appstudio-tekton-catalog/data-acceptable-bundles:latest
      - github.com/release-engineering/rhtap-ec-policy//data

      # This is the one additional data source
      # See https://github.com/simonbaird/securesign-ec-config/tree/main/policy-data
      - github.com/simonbaird/securesign-ec-config//policy-data?ref=main

    config:
      include:
        - '@redhat'
      exclude:
        - hermetic_build_task
        - tasks.required_tasks_found:prefetch-dependencies
----

That custom data source should be kept updated as new Tekton task bundles are pushed, perhaps via some automation or using https://enterprisecontract.dev/docs/ec-cli/main/ec_track_bundle.html[`ec track bundle`].

The customized policy can be provided to EC with the `--policy` parameter, and should allow custom tasks to validate using the new data source.

To confirm it works as expected, you can run EC locally, for example:

[,bash]
----
$ export IMAGE=quay.io/redhat-user-workloads/rhtas-tenant/rhtas-stack-1-0-beta/rekor-server@sha256:7fb224c62e5ea5b43ad123529487f07553626e9cd1f908d515114ee414679d6b

$ export POLICY=github.com/simonbaird/securesign-ec-config

$ ec validate image --image $IMAGE --policy $POLICY --public-key <(cat key.pub) --ignore-rekor --output data=data.yaml --output policy-input=policy-input.json --output yaml | yq .components[].violations
---

Note that the `--output data` and `--output policy-input` flags are not strictly necessary, but may be helpful for troubleshooting.
